jwt:
  secret: "your_jwt_secret_key"
  ttl: 3600 # Token Time To Live in seconds (1 hour)

server:
  host: "0.0.0.0"
  port: 8080

database:
  host: "192.168.178.211"
  port: 5432
  user: "fimuver_user"
  password: "fimuver_password"
  database: "fimuver_db"
  sslmode: "disable"

tvdb:
  tvdb_api_key: ""
  base_url: "https://api4.thetvdb.com/v4"
